name: rna-seq-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - snakemake-minimal
  - star
  - samtools
  - subread
  - trim-galore
  - fastqc
  - multiqc
  - r-base
  - r-deseq2
  - r-ggplot2
  - r-pheatmap
