#!/bin/bash
# =============================================================================
# HOMER promoter motif enrichment — all 8 pairwise comparisons
# =============================================================================
# Uses HOMER v5.1 with the JASPAR2024 CORE plants non-redundant motif library
# (805 PWMs). All comparisons use 2 kb upstream TSS FASTA files generated by
# extract_promoters.py / extract_all_prr_promoters.py.
#
# TO ADAPT FOR A NEW DATASET:
#   1. Update FA_DIR to point to your FASTA directory
#   2. Update OUT_BASE to your desired output directory
#   3. Update MOTIFS to your HOMER-format motif file
#   4. Edit the run_homer() calls below — each takes:
#        run_homer <name> <foreground.fa> <background.fa>
#      where foreground and background are FASTA filenames relative to FA_DIR
#
# JASPAR2024 HOMER-format motif file was converted from the MEME format using:
#   python meme_to_homer.py JASPAR2024_CORE_plants_non-redundant.meme \
#          > JASPAR2024_plants_homer.motif
# =============================================================================

source ~/miniconda3/etc/profile.d/conda.sh
conda activate nlr_pipeline

HOMER=~/miniconda3/envs/nlr_pipeline/share/homer/bin/findMotifs.pl
FA_DIR=/users/fyp/fyp5/project/PRJNA945175/promoters/timepoint_model_may2026_v2
OUT_BASE=/users/fyp/fyp5/project/PRJNA945175/promoters/homer_results_may2026_v2
MOTIFS=/tmp/JASPAR2024_plants_homer.motif
MLOG=/tmp/homer_master_all8.log

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$MLOG"; }

run_homer() {
    local name=$1 fg=$2 bg=$3
    local outdir="${OUT_BASE}/${name}"
    mkdir -p "$outdir"
    log "START: $name  FG=${fg}  BG=${bg}"
    perl $HOMER \
        "${FA_DIR}/${fg}" fasta "$outdir" \
        -fasta "${FA_DIR}/${bg}" \
        -nomotif \
        -mknown $MOTIFS \
        > "/tmp/homer_${name}.log" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then
        log "DONE: $name (exit 0)"
    else
        log "FAILED: $name (exit $rc)"
    fi
    return $rc
}

log "=== HOMER — JASPAR2024 plants only (-nomotif -mknown), all 8 comparisons ==="
log ""

# --- Biological question 1: Receptor class identity ---
# 1. NLR class vs expressed genome background
run_homer nlr_vs_nonNLR \
    all_nlr_promoters_2kb.fa \
    all_nondeg_expressed_promoters_2kb.fa || exit 1

# 2. PRR class vs expressed genome background
run_homer prr_vs_nonPRR \
    all_prr_promoters_2kb.fa \
    all_nondeg_expressed_promoters_2kb.fa || exit 1

# --- Biological question 2: Virus responsiveness ---
# 3. DEG NLRs vs non-DEG expressed NLRs
run_homer degNLR_vs_nondegNLR \
    deg_nlr_promoters_2kb.fa \
    nondeg_nlr_expressed_promoters_2kb.fa || exit 1

# 4. DEG PRRs vs non-DEG expressed PRRs
run_homer degPRR_vs_nondegPRR \
    deg_prr_promoters_2kb.fa \
    nondeg_prr_expressed_promoters_2kb.fa || exit 1

# --- Biological question 3: Cross-class divergence ---
# 5. DEG NLRs vs DEG PRRs
run_homer degNLR_vs_degNonNLR \
    deg_nlr_promoters_2kb.fa \
    deg_prr_promoters_2kb.fa || exit 1

# 6. DEG PRRs vs DEG NLRs (mirror comparison)
run_homer degPRR_vs_degNonPRR \
    deg_prr_promoters_2kb.fa \
    deg_nlr_promoters_2kb.fa || exit 1

# --- Biological question 4: Direction of response ---
# 7. Upregulated PRR DEGs vs downregulated PRR DEGs
run_homer upPRR_vs_downPRR \
    up_prr_deg_promoters_2kb.fa \
    down_prr_deg_promoters_2kb.fa || exit 1

# 8. Upregulated NLR DEGs vs downregulated NLR DEGs
run_homer upNLR_vs_downNLR \
    up_nlr_deg_promoters_2kb.fa \
    down_nlr_deg_promoters_2kb.fa || exit 1

log ""
log "=== All 8 comparisons complete ==="
